reader_preference:
	gcc -Wall -o reader_preference reader_preference.c -lpthread

writer_preference:
	gcc -Wall -o writer_preference writer_preference.c -lpthread

fairness:
	gcc -Wall -o fairness fairness.c -lpthread

clean:
	rm reader_preference writer_preference fairness
