mutex:
	gcc -Wall -o mutex mutex.c -lpthread

mutex_and_cond:
	gcc -Wall -o mutex_and_cond mutex_and_cond.c -lpthread

semaphore:
	gcc -Wall -o semaphore semaphore.c -lpthread

clean:
	rm mutex mutex_and_cond semaphore
